### ISSUE TITLE
"Forum" > "start letter" only looks for capitals

### ISSUE THREAD

**Issue by vendethiel** [MightyGorgon/icy_phoenix#100]
When you enable the "search by first topic title letter" (global switch + per forum), it'll only look for capital letters as the first letter.

Looks like a bug to me, can you confirm MG? You might want it that way

**Comment by vendethiel** [comment]
I think we should **not** use LIKE for this feature, and use SUBSTRING.

**Comment by MightyGorgon** [comment]
Thanks, I have fixed it on my local repo.
