### ISSUE TITLE
"Bottom" button on viewtopic posts doesn't work

### ISSUE THREAD

**Issue by vendethiel** [MightyGorgon/icy_phoenix#105]
When you're on viewtopic, there exists little icons "top and bottom" next to each posts. Top works, but not bottom. 
I guess it's missing an anchor on my theme (prosilver)

**Comment by vendethiel** [comment]
Actually, it's just because `<a id="bottom"></a>` needs content (for example, `&nbsp;`, with `style="font-size: 0"`)

**Comment by vendethiel** [comment]
the "proposed" fix is linked just above.

**Comment by MightyGorgon** [comment]
I have fixed it, thanks.
