### ISSUE TITLE
[discuss] What to do with clean name

### ISSUE THREAD

**Issue by vendethiel** [MightyGorgon/icy_phoenix#120]
>  I still think "clean name" should be a hidden field... I get why it's there (SEO and everything), but I think most users don't care about that. Maybe make it a switch? Not sure.

Should we just allow it as a feature for "advanced users"? in the admin panel? not sure

**Comment by MightyGorgon** [comment]
You are right, I need to hide those fields... they were intended even for assigning topics to a precise address. But since they are not used, it should be better to hide them.

**Comment by vendethiel** [comment]
yes, I gather their use, and I think it's interesting for very-advanced users (maybe they want to optimize their SEO?), but not for everybody :).

**Comment by MightyGorgon** [comment]
The real issue is that the whole things just doesn't work... because there are no proper htaccess rules to deal with these kind of url. I will just hide those fields when I have some time.

**Comment by vendethiel** [comment]
Okay, good to know still, thanks. Maybe open an issue here, maybe we'll have an idea at some point?

**Comment by MightyGorgon** [comment]
I have moved the field to an hidden INPUT for now...
