### ISSUE TITLE
Translate of blocks

### ISSUE THREAD

**Issue by KratorD** [MightyGorgon/icy_phoenix#121]
Hello. 

I think that exists an error with the possibility of "translate" the title of blocks. 
For example, I'm using spanish language for IP, well, I edit the file /language/lang_spanish/lang_main.php and change the translate of "Shoutbox".
Then, I go to ACP, and edit the page where shoutbox is present. Select "Localizate Title Bar".
Save the data and refresh the page... The translate is not showed.

I think that the the title that show the page is always the title in ACP.

Thanks.

**Comment by vendethiel** [comment]
I'll try to check tomorrow... Can you try using an UPPERCASE lang key for now? Thanks

**Comment by MightyGorgon** [comment]
You need to edit this file `language/lang_spanish/lang_blocks.php`

**Comment by KratorD** [comment]
Correct!
It's a problem with the spanish translate.

The file lang_blocks.php (english):
'cms_block_shoutbox' => 'Shoutbox',

The file lang_blocks.php (spanish):
'Title_shoutbox' => '<a href="shoutbox_max.' . PHP_EXT . '?sid=' . $user->data['session_id'] . '">Chat</a>',

The "title" is different, so IP dont found the translate string.
Thanks. You can close this ticket
