### ISSUE TITLE
Groups Permissions

### ISSUE THREAD

**Issue by MWE001** [MightyGorgon/icy_phoenix#132]
Not really an issue, nor is it a bug. JUST an observation.

Ig you create a new group as usual and submit it, you can go back to groups management where you can create a new group. on the groups you already have created you have the Management / Permissions thing which is cool. However, in the ACP slide menu on the left, you have 2 options. Management and permissions. The permissions is kind of redundant as that option is already available in the management tab.

![screenshot_46](https://cloud.githubusercontent.com/assets/2566493/18619258/732bbe52-7dbd-11e6-98a1-7fa8840ff49c.jpg)

Not really a big deal, just something I noticed. :-) Take care fellas!

**Comment by MightyGorgon** [comment]
Thanks for your suggestion, I will think about this.

**Comment by vendethiel** [comment]
Does that mean we could fold Groups into the Users tab?

**Comment by MightyGorgon** [comment]
Honestly I like having Groups tab there... I would keep things as they are now if you don't mind. :-)

**Comment by vendethiel** [comment]
Definitely.
