### ISSUE TITLE
White Ugly Background Behind the Clock

### ISSUE THREAD

**Issue by MWE001** [MightyGorgon/icy_phoenix#135]
If you are like me and in to time, you will use the clock block on your site. Well, most recently, our transparent backgrounds turned solid white in IE and Firefox and turned a solid black on Chrome as far as I could tell.

The fix is very simple. In the clock_block.tpl file ,  you will find `<param name="wmode" value="transparent">`

This is not good enough anymore. Immediately under that param line you will find the embed tag. You must add the following `wmode="transparent"`  to the embed to make it look something like this:

`<embed type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" width="130" height="130" name="clock" src="{FULL_SITE_PATH}/templates/dark/images/dark/clock_blue_dark.swf" bgcolor="#ffffff" quality="high" swLiveConnect="true" allowScriptAccess="samedomain" wmode="transparent"></embed>
`

There you go. Notice my clock path is different. I am using my own flash clock. But this also will fix the standard clock that come with IP package.

Enjoy!

![clock](https://cloud.githubusercontent.com/assets/2566493/18873460/36c5be80-8485-11e6-9635-b230a41aacff.jpg)

**Comment by MWE001** [comment]
And from what I understand, if the wmode transparent thing don't work, the flash file might need to be republished with the `wmode='opaque'` 

I have not ran in to the need to republish any flash files yet.

**Comment by MWE001** [comment]
Ahh my bad guys. Now that I am good and awake, I just noticed you had the bg set to #FFFFFF . Sorry about that. This is a useless Issue opened by me. 

BUT, at any rate, if you ever remove the white background, this fix will work. I tried it on a IMPortal block and it worked great.

**Comment by MightyGorgon** [comment]
Thank you very much my friend! :-)
