### ISSUE TITLE
mySQLi driver

### ISSUE THREAD

**Issue by vendethiel** [MightyGorgon/icy_phoenix#141]
I have a working branch. @MightyGorgon should I open a PR for it?

Makes IP work on php 7.1+

**Comment by MightyGorgon** [comment]
Let me test it...

**Comment by vendethiel** [comment]
Yes. I will open a branch tomorrow.

**Comment by vendethiel** [comment]
Oh uh. I totally said the wrong thing.

**Comment by vendethiel** [comment]
I meant a mysqli... Not sqlite...
