### ISSUE TITLE
The Template Class compatible with 3.2.x

### ISSUE THREAD

**Issue by orynider** [MightyGorgon/icy_phoenix#146]
Hi,

Take a look at:
https://github.com/MightyGorgon/icy_phoenix/blob/master/includes/template.php

And:
https://github.com/Mx-Publisher/mxpcms/blob/master/includes/template.php

Specially at function compile_code() :-)

**Comment by vendethiel** [comment]
It has comments from MG, yes. What’s the purpose of this issue?

**Comment by orynider** [comment]
I see that You added TAG_HOOK. You could add INCLUDEJS and INCLUDECSS by merging the two.

**Comment by MightyGorgon** [comment]
Thanks for your suggestion, but in TPL it's already possible to include anything by using PHP, what's the purpose to add INCLUDEJS and INCLUDECSS? In Icy Phoenix there is also a specific way for doing that by using these vars (includes/template.php):
	var $css_style_include = array();
	var $css_include = array();
	var $js_include = array();

The way to use those is something like this:
		$css_temp = array('my_css.css');
		$template->css_include = array_merge($template->css_include, $css_temp);
		unset($css_temp);

So every CSS and JS is properly included in the header of the HTML.

**Comment by orynider** [comment]
The suggestion comes after I seen that any phpBB 3.2.x style can work also with MXP ignoring the events atm. This was happening 15 years ago when new users uploaded phpBB2 templates in MX-Portal 2.7 and then asked for support since they had problems with the navigation. In reality just some template files are needed from the phpBB style. 
This was funny to let users decide were to upload each type of style. :-)

There is also the lang() function that now works by str_replace it back to "L_..." and the events that I most do as in 3.2.x so that I can make styles for both CMS and Forums.

**Comment by vendethiel** [comment]
Icy Phoenix already has support for `L_` replacement (I think eXtreme Styles adds that, not sure).

**Comment by vendethiel** [comment]
phpBB 3.1 uses a template system based on Twigm and rewrites old-style construct with new style. It's 100% different.
