### ISSUE TITLE
Deprecated: Methods

### ISSUE THREAD

**Issue by Triedge** [MightyGorgon/icy_phoenix#159]
- **Deprecated**: Methods with the same name as their class will not be constructors in a future version of PHP; sql_db has a deprecated constructor in G:\AppServ\www\icy_phoenix\includes\db\mysql.php on line 28

- **Deprecated**: Methods with the same name as their class will not be constructors in a future version of PHP; acm has a deprecated constructor in G:\AppServ\www\icy_phoenix\includes\class_cache.php on line 62

**Comment by vendethiel** [comment]
It is time we update this.

What’s your PHP version?

**Comment by Triedge** [comment]
PHP Version 7.1.1

**Comment by MightyGorgon** [comment]
I should have fixed this.

**Comment by Triedge** [comment]
oh, thx very much!
