### ISSUE TITLE
Strict standards: Non-static method utf_normalizer::nfkc() should not be called statically in includes\utf\utf_tools.php on line 1663

### ISSUE THREAD

**Issue by vendethiel** [MightyGorgon/icy_phoenix#37]
The error message appears on install.

Solution : change these methods to be static.

**Comment by saidbakr** [comment]
I have two copies on the same server, one on the main domain and the other on a sub directory of  sub-domain i.e example.com and test.example.com/base/phpbb3 of phpbb3.0.13 pl1. the one on the main domain works fine without this error but on the sub-domain it generates this error.

**Comment by vendethiel** [comment]
This is Icy Phoenix, a fully-integrated CMS+forum system, not phpbb3. Try phpbb.com
