### ISSUE TITLE
Gmail social connect

### ISSUE THREAD

**Issue by vendethiel** [MightyGorgon/icy_phoenix#66]
I think I looked at that some time ago, but I abandoned. Reading the code again now, I can't remember why I did that... I think @GabrielAnca did a good job.

**Comment by vendethiel** [comment]
@MightyGorgon see ^

**Comment by MightyGorgon** [comment]
Yes :-)

**Comment by vendethiel** [comment]
@MightyGorgon where should I put the library? I'm gonna go ahead and create a "vendor" directory for now
