### ISSUE TITLE
ip_users social fields

### ISSUE THREAD

**Issue by vendethiel** [MightyGorgon/icy_phoenix#67]
https://github.com/MightyGorgon/icy_phoenix/commit/405a99f2be6e432eb0cbb0acb83bfb1b0f65524a#commitcomment-8348480

> > Mighty Gorgon said:
> > Yes, maybe those are obsolete... maybe we should even merge all social accounts within one single fields in DB, just to save space for unused columns and spare extra work in the future... in this way new social fields could be customized without even adding any column to DB.
> > 
> > What do you think?
> > 
> > Would you like to work on this ?
> > Informpro said:
> > This is definitely something to do! Though one could argue it conflicts with the ability to add field to the profile, maybe?
> 
> Also, something not to forget: if we do as you say, we need to be very careful. Maybe store them as json or something, but not as pipe-separated values (if we DID store them as pipe-separated values, we'd need to walk the entire DB everytime the admin adds/removes a field, to remove the value. Pretty bad!). Storing it in one column also means no search, but I think it's okay.

**Comment by MightyGorgon** [comment]
I don't understand why you referenced this... you were partially right about serializing even if we could have found other solutions to this.

**Comment by vendethiel** [comment]
Well, mostly because of the "no answer" part... I posted the results I got when I tried working on it: that it broke user search. And that I'd have needed your ideas on how to handle that

**Comment by vendethiel** [comment]
If we allow ourselves recent MySQL versions we can just use JSON to store everything. No serialization needed.

**Comment by vendethiel** [comment]
I have started development to use a JSON array instead. It shouldn't require too many changes.

**Comment by MightyGorgon** [comment]
Ok, let me know... :-)
