### ISSUE TITLE
Release 2.1

### ISSUE THREAD

**Issue by vendethiel** [MightyGorgon/icy_phoenix#68]
2.0 was more than 2 years ago :(. Even if there isn't too many improvements to list, we should probably release 2.1 soon-ish. (plus it looks like we're keeping up with phpb3.1's release date hehe... Just kidding)

@MightyGorgon I think you were working on something pretty big? Do you know when you'll have time to wrap it up?

**Comment by vendethiel** [comment]
@MightyGorgon do you plan to do this, or do you actually want to discontinue Icy Phoenix now?

**Comment by MightyGorgon** [comment]
I've been busy in coding a plugin for a customer... I have few edits to commit.

Unfortunately the template isn't going to be updated anytime soon... so if we want to release an updated, we need to do with current template system.

I'll try to commit file changes tonight if I have time so you can check them and you can try the install procedure.

**Comment by vendethiel** [comment]
Please release 2.1 or 3.0 ASAP. The fact that the last release was 2+ years ago makes it somewhat hard to say stuff is coming up next.. Thanks :)
