### ISSUE TITLE
Topic preview

### ISSUE THREAD

**Issue by vendethiel** [MightyGorgon/icy_phoenix#92]
This should be relatively easy, and I've found a use for this feature many times myself.

The basic premisce is that you can see the first **and/or** last post of a topic by hovering over it, allowing to see what the topic is about.

I've implemented such a feature on EzArena, so I know exactly how I'm going to do it (I'll try to work on that in january).
This is **not** going to add SQL queries, only a `LEFT JOIN ip_posts fp WHERE fp.post_id = t.first_post_id` (fp = first post) (and also probably a column for the poster's information)

**Comment by vendethiel** [comment]
This should be an extension

**Comment by MightyGorgon** [comment]
You can code it if you wish, it shouldn't be tough.

Maybe it's better to code it as a config switch instead of an extension/plugin, what do you think?

**Comment by vendethiel** [comment]
I think it could make for a nice extension "demo" so that, if people want to create more, it's easy for them.

**Comment by vendethiel** [comment]
Gonna mark it as a Future plugin.

**Comment by vendethiel** [comment]
A future extension. We now have triggers and template hooks, so it is doable.
